### ISSUE TITLE
Hexdocs issues

### ISSUE THREAD

**Issue by sodapopcan** [srcrip/live_toast#1]
- `@doc` examples aren't 4-space indented therefore are'nt rendering as code
- Code links (`</>`) are broken

**Comment by srcrip** [comment]
I think I've fixed the issues now in https://github.com/srcrip/live_toast/commit/a141942f1138c25db6c25f92c3f6c27ebe9a88c6, will you let me know if it looks ok to you now?

**Comment by srcrip** [comment]
Closing as I think it's resolved but please reopen if not @sodapopcan, and thanks!
