### ISSUE TITLE
`put_toast` do not work with `push_navigate` 

### ISSUE THREAD

**Issue by luislhsc** [srcrip/live_toast#11]
Hey, thank you for all your effort on this lib! It is awesome, very customizable and looks great.

On thing I noticed, is that it only works on my live components/view if I use  `push_patch`

```elixir
case create_thing(socket, params) do
      {:ok, thing} ->
        socket
        |> put_toast(:success, "Thing was created!")
        |> push_patch(to: ~p"/app/thing/#{thing.id}")
        |> noreply()

      {:error, changeset} ->
        socket
        |> assign(:form, to_form(changeset))
        |> noreply()
    end
```

If I change it to be `push_navigate` instead of patch: 
```elixir 
        socket
        |> put_toast(:success, "Thing was created!")
        |> push_navigate(to: ~p"/app/thing/#{thing.id}")
        |> noreply()
```

The toast does not work.  Is it a bug or is there a limitation to make it work with push_navigate? 
Just a note, the `put_flash` from Phoenix/Liveview works on push_patch/push_navigate/redirect.

**Comment by srcrip** [comment]
This seems to be the same thing noticed in https://github.com/srcrip/live_toast/issues/9... I'm going to take a look at it today. If you have a minimal repro it would help a lot though.

**Comment by srcrip** [comment]
ok I have a plan for how to implement this. I should have it ready in a few days.

**Comment by srcrip** [comment]
I'm going to close this in favor of https://github.com/srcrip/live_toast/issues/9 cause it was opened first.
