### ISSUE TITLE
Module 'live_toast' missing declaration file

### ISSUE THREAD

**Issue by tylerbarker** [srcrip/live_toast#12]
I noticed that importing live_toast in a TypeScript file is requiring a `// @ts-ignore` at the moment. Is this as simple as adding the corresponding `.d.ts` file to the repo? I'm not familiar with Ava.

![liveToastTypes](https://github.com/srcrip/live_toast/assets/10856628/af11b46d-7bad-4d9d-b532-9eab3c4330a5)

**Comment by srcrip** [comment]
Yup I just noticed that myself. I think you're right, I just need to commit a `.d.ts`.

**Comment by srcrip** [comment]
I will add it but if you send a PR before I get to it I will merge it if you want the contributor badge!

**Comment by srcrip** [comment]
Completed in #15
