### ISSUE TITLE
Support for i18n

### ISSUE THREAD

**Issue by elephantoss** [srcrip/live_toast#13]
Add the ability to provide translations, using gettext:
- Something went wrong
- We can't find the internet
- Info
- Error
- Attempting to reconnect
- Hang in there while we get back on track

I'll be glad to work on this if that's ok.

**Comment by srcrip** [comment]
Thank you for the issue @elephantoss! Definitely agree that would be nice to have. You can definitely make a PR if you want! If not I'll try to knock it out. 🙂

**Comment by elephantoss** [comment]
@srcrip I'll give it a try. I'll let you know if I get stuck
