### ISSUE TITLE
Undefined Function `stream_configure/3`

### ISSUE THREAD

**Issue by curtisault** [srcrip/live_toast#14]
Ok, I'd like to use this in a project I'm working on but I'm having a bit of an issue.

## Error

Error info:

> error: undefined function stream_configure/3 (expected LiveToast.LiveComponent to define such a function or for it to be imported, but none are available)
>   lib/live_toast/live_component.ex:12: LiveToast.LiveComponent.mount/1
> 
> 
> == Compilation error in file lib/live_toast/live_component.ex ==
> ** (CompileError) lib/live_toast/live_component.ex: cannot compile module LiveToast.LiveComponent (errors have been logged)
> 
> could not compile dependency :live_toast, "mix compile" failed. Errors may have been logged above. You can recompile this dependency with "mix deps.compile live_toast --force", update it with "mix deps.update live_toast" or clean it with "mix deps.clean live_toast"

<img width="1728" alt="image" src="https://github.com/srcrip/live_toast/assets/7681962/c0804e4e-16b2-4c83-80a2-19fb2c2d1e71">

Obviously, this looks like I'm missing the Phoenix LiveView release that includes the [`stream_configure/3`](https://github.com/phoenixframework/phoenix_live_view/blob/cbc7b0bbc7d34bcc91ef16cacc27e1caba6e52a6/lib/phoenix_live_view.ex#L1729) functionality.

But, I've double checked the [dependencies on the hex page](https://hex.pm/packages/live_toast) and compared them to my mix.lock file and I have all the necessary dependencies which at the time of this writing is:

> [ecto](https://hex.pm/packages/ecto) >= 3.11.0
> [phoenix](https://hex.pm/packages/phoenix) >= 1.7.0
> [phoenix_live_view](https://hex.pm/packages/phoenix_live_view) >= 0.18.0

<img width="1728" alt="image" src="https://github.com/srcrip/live_toast/assets/7681962/a24e5dfe-05c7-4fc9-a4c1-c792ebfe3c94">

So I'm having a bit of a conundrum. Could the issue be deeper and bubbling up to this?

## Steps I've Tried

1. Forcing Recompilation: `mix deps.compile live_toast --force`
2. Forcing a full clean: `mix do deps.clean --all, deps.get, compile`
3. Updating all deps and recompiling: `mix do deps.update --all, compile`
4. Revisited the installation instructions again just in case I missed anything.
5. I've cloned the library locally and compiled _just to be sure_ and it compiles just fine.

🫠

**Comment by curtisault** [comment]
@srcrip I've figured out the issue. You **must** have `phoenix_live_view` v0.20.0 in order to use `stream_configure/3`.

See [v0.20.0 Changelog](https://hexdocs.pm/phoenix_live_view/changelog.html#deprecations-4)

I would have opened a PR but I don't have permissions.

**Comment by srcrip** [comment]
Thanks for the issue @curtisault!

You should be able to open a PR... did you fork first, push your commit to your fork, and then PR from the fork to here?

Alternatively if it still doesn't work for you I can make the change you're recommending if you let me know what that is.

**Comment by curtisault** [comment]
> You should be able to open a PR... did you fork first, push your commit to your fork, and then PR from the fork to here?

I just cloned. I'll fork and submit a patch something this evening. Thanks! 🙌

**Comment by srcrip** [comment]
Thank you!
