### ISSUE TITLE
Request: Support for override button classes

### ISSUE THREAD

**Issue by mike1o1** [srcrip/live_toast#20]
It would be nice if we could override the classes for the button markup, similar to how we are able to set the `toast_class_fn`. In my case, I'm setting dark mode specific background color (black), which kind of conflicts with the `text-black/50` that's getting applied in the current markup.

Happy to submit a PR if others have interest in this.

**Comment by FranzVDB** [comment]
Would be nice, my hack was a global css selector that overrides the color on button.

**Comment by srcrip** [comment]
@mike1o1 @FranzVDB the option *I* would use is TW classes that deeply select, like if you wanted to make the button red for instance you could do: `[&_button]:bg-red-400`.

Of course you don't *have* to use TW, as @FranzVDB pointed out you can put a regular class called `.toast` on through `toast_class_fn` and select it with regular css:

```css
.toast {
  button {
    background: red;
  }
}
```

I'll close this issue cause I think using CSS itself is a fine way of targeting the parts of the toast itself. If you find something that you can't do with just CSS for some reason feel free to reopen or open a new issue. Thank you!
