### ISSUE TITLE
Flash messages not appearing after `push_navigate`

### ISSUE THREAD

**Issue by sevenseacat** [srcrip/live_toast#25]
I think this may be related to #9 but I'm not sure.

Code like the following in a LiveView:

```elixir
socket
|> LiveToast.put_toast(:info, "Artist saved successfully")
|> push_navigate(to: ~p"/")
```

Won't render a toast message, as the LiveToast.LiveComponent never receives the update with the new toast (as it's been torn down and remounted after the navigate).

This is a super common pattern that needs support!

**Comment by rmand97** [comment]
I have the same problem

**Comment by srcrip** [comment]
@sevenseacat and @rmand97 There is now a PR that aims to address this, if you'd like to test the branch in my PR that would be great!

**Comment by sevenseacat** [comment]
Unfortunately I removed live_toast a while ago, as it wasn't usable to me without this feature. I hope it works though!

**Comment by srcrip** [comment]
No worries! I'll leave this issue open until #28 is merged. @sevenseacat let me know if there's anything else I can add that would enable you to use it in the future.

**Comment by srcrip** [comment]
Closing now since #28 is implemented.
