### ISSUE TITLE
Will it be possible to relax the gettext version? 

### ISSUE THREAD

**Issue by wkirschbaum** [srcrip/live_toast#30]
```
Because live_toast >= 0.7.0 depends on gettext ~> 0.24.0 and your app depends on gettext ~> 0.26, live_toast >= 0.7.0 is forbidden.
```

Is it necessary to only depend on 0.24?

**Comment by srcrip** [comment]
Completed in 0983a4dde23528417c9ea33180d6873b620fd7a8. I will release a new version once I have some of the minor fixes/requests that have open issues done so if you'd like you can point to `master` for now. Thank you @wkirschbaum!
