### ISSUE TITLE
Unable to dismiss or remove

### ISSUE THREAD

**Issue by brainlid** [srcrip/live_toast#4]
## Background
I added LiveToast following the guide to an existing Phoenix application.

In my `app.js`, I configured the duration and maxItems following the guide. In my case, it looks like this:

```js
// the duration for each toast to stay on screen in ms
const duration = 4_000
// how many toasts to show on screen at once
const maxItems = 3

// Setup LiveToast
Hooks.LiveToast = createLiveToastHook(duration, maxItems)
```

I added the following to my app layout:

```
    <LiveToast.toast_group
      flash={@flash}
      connected={assigns[:socket] != nil}
      toast_class_fn={&Web.LiveToastHelper.toast_class_fn/1}
      corner={:top_right}
    />
```

## Behavior Problem
It correctly displays on top, but takes the full width. I inspected the styles for it and the `toast-group` DOM id has the class `w-full`.

![image](https://github.com/srcrip/live_toast/assets/808984/1e6a5c17-740c-46f1-a8e4-5fb25b6c3a58)

Also, the `flash-info` DOM id has a `data-duration=0` attribute, which presumably means "don't go away", but is should have had a duration of 4000.

The info toast was created using the Phoenix `put_flash` and it is just a regular flash message. However, there is no "x" like in the demo to be able to dismiss the message manually. Clicking the message does nothing either.

## Summary 
It isn't displaying as expected (don't want full width), it isn't auto-dismissing as expected, and it can't be dismissed manually.

I expect there's a documentation piece missing or I have something in the project that's broken it somehow.

**Comment by sodapopcan** [comment]
I think you just forgot the Tailwind piece.  Add the following to your tailwind.config.js:

```javasciript
    '../deps/live_toast/lib/**/*.*ex',
```

I made the same mistake 😃

**Comment by brainlid** [comment]
Thanks @sodapopcan for pointing me in that direction. 

It turns out that when I copied the Tailwind config into my app, I didn't adjust it for being in an Elixir Umbrella project.

In my case it needed to be:

```
    "../../../deps/live_toast/lib/**/*.*ex"
```

Thanks for speaking up!

I might suggest a README note for umbrella apps (I realize they aren't as common either).

**Comment by srcrip** [comment]
I will put that exact disclaimer in now

**Comment by srcrip** [comment]
I have now pointed that out in the docs
